import mongoose from "mongoose";

const notificationSchema = new mongoose.Schema({
  notification_id: { type: String, default: () => new mongoose.Types.ObjectId().toString(), unique: true },
  recipient_ids: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  read_by: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  batch_id: { type: mongoose.Schema.Types.ObjectId, ref: "BirdBatch" },
  type: {
    type: String,
    enum: [
      "disease",
      "market",
      "tip",
      "vaccination_reminder",
      "vaccination_stock_reminder",
      "r2b_reminder",
      "deworming_reminder",
      "booster_reminder",
      "vaccination_completed",
      "vaccination_missed",
      "vaccination_rescheduled",
      "mortality_alert",
      "vaccine_overdue",
      "user_registration_pending",
      "user_approved",
      "user_rejected",
      "approval_reminder",
      "loan_applied",
      "loan_approved",
      "loan_rejected",
      "loan_due_reminder",
      "loan_disbursed",
      "vaccination_stock_reminder",
      "vaccination_stock_monthly_reminder",
      "weekly_stock_reminder",
    ],
    required: true,
  },
  title: { type: String },
  message: { type: String, required: true },
  channel: { type: String, enum: ["push", "in-app", "sms", "whatsapp"], default: "push" },
  status: { type: String, enum: ["pending", "sent", "failed"], default: "pending" },
  sent_at: { type: Date },
  created_at: { type: Date, default: Date.now },
  createdAt: { type: Date, default: Date.now },

  hamlet: { type: String },
  shg_name: { type: String },
  shg_names: [{ type: String }],
  failure_reason: { type: String },
  payload: { type: mongoose.Schema.Types.Mixed },
});

export default mongoose.model("Notification", notificationSchema);
